In [1]:
!which python
!nvidia-smi

/home/asa/miniconda3/envs/PyTorch-Development/bin/python
Sat Aug 17 18:23:06 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.58.02              Driver Version: 555.58.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   46C    P0             16W /   80W |       8MiB /   6141MiB |      0%      Default |
|                                         |                        |               

In [6]:
# Checking the GPU availablity
import torch

if torch.cuda.is_available():
    print(f"GPU device : {torch.cuda.get_device_name()}")
else:
    print("CUDA is not available. No GPU detected.")

GPU device : NVIDIA GeForce RTX 4050 Laptop GPU


In [7]:
# Installing the required packages
!pip install pandas numpy matplotlib scipy

In [2]:
# Importing thw requires packages
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

In [3]:
# Checking the torch version
torch.__version__

'2.4.0'

In [42]:
# Let's Code.

# Scalar
t1 = torch.tensor(2).to(device='cuda')
t1

tensor(2, device='cuda:0')

In [41]:
t1.new_tensor(23).item()

23

In [47]:
# Dimension of a tensor
# Both does the same stuff (fn & property)
t1.ndimension(), t1.ndim

(0, 0)

In [52]:
# Vector
t2 = torch.tensor([1,2,3])
t2

tensor([1, 2, 3])

In [53]:
# Getting the shape, size, rank
t2.shape, t2.size(), t2.ndim

(torch.Size([3]), torch.Size([3]), 1)

In [54]:
# Matrix
t3 = torch.tensor([[1,2],
                   [3,4]])
t3

tensor([[1, 2],
        [3, 4]])

In [55]:
t3.shape

torch.Size([2, 2])

In [56]:
t3.size()

torch.Size([2, 2])

In [57]:
# Total no. of elements in the tensor
t3.numel()

4

In [58]:
# getting the dtype and device it is loaded
t3.dtype, t3.device

(torch.int64, device(type='cpu'))

In [66]:
# tensor / multi-dim matrix
t4 = torch.tensor([[[1,2],[3,4],[9,0]],[[5,6],[7,8],[9,8]]])
t4

tensor([[[1, 2],
         [3, 4],
         [9, 0]],

        [[5, 6],
         [7, 8],
         [9, 8]]])

In [67]:
t4.shape, t4.ndim, t4.dtype, t4.device, t4.numel()

(torch.Size([2, 3, 2]), 3, torch.int64, device(type='cpu'), 12)

In [80]:
# Memory layout of a tensor
t4.layout

torch.strided